### PR TITLE
[WIP] Pull UPC++ test sources + Makefile from Spack rather than embedding

### PR DESCRIPTION
**Pull request by bonachea**
### THIS PULL REQUEST CONTAINS UNTESTED SCRIPT CODE

**I've marked this pull request as WIP, because I don't trust my ability to replicate the environment used to run these scripts inside the containers.  Someone with a working environment needs to validate the script changes here operate as intended.**

The UPC++ tests currently embedded on master are stale and break with
the current 2021.9.0 UPC++ release. This changes the testsuite to pull
the latest tests directly from the Spack install of UPC++, which should
always be compatible with the installed version.

Other tweaks:

1. Use the `make run` convenience alias to perform execution
2. Default to smp-conduit backend unless one is specified in environment,
   which should ensure job spawning always trivially works (for anything
   except cross-compiled systems).

### CODE REVIEW

**Comment by bonachea** [comment]
@sameershende @wspear @eugeneswalker are one of you able to easily validate the scripting in this PR?

Feel free to push update commits if there are bugs.

**Review by wspear — COMMENTED** [review]
This works well. We had a missing device error in the in-container tests previously (/proc/device-tree/cpus) but that is no longer happening. 

I do see the following warning when running in our container but this may be expected behavior:

```
upcxx::init():
> WARNING: Requested UPC++ shared heap size (128 MB) is larger than the GASNet segment size (10232 KB). Adjusted shared heap size to 10232 KB.
```

Also, the ./clean.sh script should probably delete the example directory. Currently it just runs make clean in the top directory which doesn't do anything. I can fix that myself after merging this if you prefer.

**Comment by bonachea** [comment]
Thanks @wspear : I just pushed the requested change to clean.sh.

The warning about the shared heap size most likely indicates that /dev/shm in the container is too small (~40MB?), which drastically limits the amount of shared heap available to UPC++ applications.

I've just checked and it appears the all the "toy" examples in this test suite _should_ be capable of running correctly within 10MB of shared heap per process, but this property is "accidental" and might not be true of a future UPC++ release. In general I'd consider this a pathologically small shared memory limit. Even simple UPC++ kernels will require alot more shared memory than this. If it's practical to expand the container's /dev/shm to something on the order of the configured physical memory size, that would be highly recommended.

**Comment by bonachea** [comment]
@wspear : Any thoughts on the comments below?

> The warning about the shared heap size most likely indicates that /dev/shm in the container is too small (~40MB?), which drastically limits the amount of shared heap available to UPC++ applications.
> 
> I've just checked and it appears the all the "toy" examples in this test suite _should_ be capable of running correctly within 10MB of shared heap per process, but this property is "accidental" and might not be true of a future UPC++ release. In general I'd consider this a pathologically small shared memory limit. Even simple UPC++ kernels will require alot more shared memory than this. **If it's practical to expand the container's /dev/shm to something on the order of the configured physical memory size, that would be highly recommended.**

**Comment by wspear** [comment]
We just launch with the default shm-size for our usual testing containers. We can start specifying larger if we run into trouble with the tests. Since this is a run-time rather than container-build-time option anyone using real UPC++ kernels can launch the container according to their needs. e.g `docker run --shm-size 8G ...`

**Comment by bonachea** [comment]
> We just launch with the default shm-size for our usual testing containers. We can start specifying larger if we run into trouble with the tests. Since this is a run-time rather than container-build-time option anyone using real UPC++ kernels can launch the container according to their needs. e.g `docker run --shm-size 8G ...`

@wspear : Thanks for the clarification. I was also asking on behalf of the other distributed images like OVA or AWS EC2, although I have not personally tested those to see what /dev/shm they provide.

**Pull request merged**
