### PR TITLE
improving butterflypack validation_tests by using cmake build

### PR DESCRIPTION
**Pull request by liuyangzhuan**
Change the build method of butterflypack tests from make to cmake.

### CODE REVIEW

**Review by wspear — APPROVED** [review]
This looks good. Thanks!

**Comment by wspear** [comment]
@liuyangzhuan I'm running into failures with the new butterflypack on NERSC's perlmutter:

```
Skipping load: Environment already setup
Skipping load: Environment already setup
-- The Fortran compiler identification is Cray 12.0.3
-- Cray Programming Environment 2.7.11 Fortran
-- Detecting Fortran compiler ABI info
-- Detecting Fortran compiler ABI info - done
-- Check for working Fortran compiler: /opt/cray/pe/craype/2.7.11/bin/ftn - skipped
-- Checking whether /opt/cray/pe/craype/2.7.11/bin/ftn supports Fortran 90
-- Checking whether /opt/cray/pe/craype/2.7.11/bin/ftn supports Fortran 90 - yes
-- Found ButterflyPACK: /gpfs/alpine/gen010/proj-shared/e4s/21.11/spack/opt/spack/cray-sles15-zen2/gcc-9.3.0/butterflypack-2.0.0-kmrrb6m44hng3i3cb34v7lptnwtxmoum/lib/cmake/ButterflyPACK/butterflypack-config.cmake (found version "2.0.0")
-- Found OpenMP_Fortran: -h omp (found version "4.5")
-- Found OpenMP: TRUE (found version "4.5")
-- Performing Test COMPILER_GNU
-- Performing Test COMPILER_GNU - Failed
-- Performing Test COMPILER_Intel
-- Performing Test COMPILER_Intel - Failed
-- Performing Test COMPILER_PGI
-- Performing Test COMPILER_PGI - Failed
-- Configuring done
-- Generating done
-- Build files have been written to: /ccs/home/wspear/gen010-scratch/testsuite/validation_tests/butterflypack
Scanning dependencies of target ie2d
[ 33%] Building Fortran object CMakeFiles/ie2d.dir/EMCURV_Module.f90.o


ftn-100 crayftn: ERROR $MAIN, File = ../../../gpfs/alpine/gen010/scratch/wspear/testsuite/validation_tests/butterflypack/EMCURV_Module.f90, Line = 18, Column = 1
  This statement must begin with a label, a keyword, or an identifier.


ftn-293 crayftn: ERROR $MAIN, File = ../../../gpfs/alpine/gen010/scratch/wspear/testsuite/validation_tests/butterflypack/EMCURV_Module.f90, Line = 18, Column = 1
  This unnamed main program unit is missing an END statement.


ftn-100 crayftn: ERROR $MAIN, File = ../../../gpfs/alpine/gen010/scratch/wspear/testsuite/validation_tests/butterflypack/EMCURV_Module.f90, Line = 20, Column = 1
  This statement must begin with a label, a keyword, or an identifier.


ftn-855 crayftn: ERROR EMCURV_MODULE, File = ../../../gpfs/alpine/gen010/scratch/wspear/testsuite/validation_tests/butterflypack/EMCURV_Module.f90, Line = 23, Column = 8
  The compiler has detected errors in module "EMCURV_MODULE".  No module information file will be created for this module.


ftn-292 crayftn: ERROR EMCURV_MODULE, File = ../../../gpfs/alpine/gen010/scratch/wspear/testsuite/validation_tests/butterflypack/EMCURV_Module.f90, Line = 24, Column = 5
  "BPACK_DEFS" is specified as the module name on a USE statement, but the compiler cannot find it.


ftn-292 crayftn: ERROR EMCURV_MODULE, File = ../../../gpfs/alpine/gen010/scratch/wspear/testsuite/validation_tests/butterflypack/EMCURV_Module.f90, Line = 25, Column = 5
  "MISC_UTILITIES" is specified as the module name on a USE statement, but the compiler cannot find it.


ftn-292 crayftn: ERROR ZELEM_EMCURV, File = ../../../gpfs/alpine/gen010/scratch/wspear/testsuite/validation_tests/butterflypack/EMCURV_Module.f90, Line = 77, Column = 7
  "BPACK_DEFS" is specified as the module name on a USE statement, but the compiler cannot find it.


ftn-113 crayftn: ERROR ZELEM_EMCURV, File = ../../../gpfs/alpine/gen010/scratch/wspear/testsuite/validation_tests/butterflypack/EMCURV_Module.f90, Line = 110, Column = 29
  IMPLICIT NONE is specified in the local scope, therefore an explicit type must be specified for data object "IMPEDENCE0".


ftn-113 crayftn: ERROR ZELEM_EMCURV, File = ../../../gpfs/alpine/gen010/scratch/wspear/testsuite/validation_tests/butterflypack/EMCURV_Module.f90, Line = 110, Column = 62
  IMPLICIT NONE is specified in the local scope, therefore an explicit type must be specified for data object "JUNIT".


ftn-113 crayftn: ERROR ZELEM_EMCURV, File = ../../../gpfs/alpine/gen010/scratch/wspear/testsuite/validation_tests/butterflypack/EMCURV_Module.f90, Line = 110, Column = 68
  IMPLICIT NONE is specified in the local scope, therefore an explicit type must be specified for data object "PI".


ftn-113 crayftn: ERROR ZELEM_EMCURV, File = ../../../gpfs/alpine/gen010/scratch/wspear/testsuite/validation_tests/butterflypack/EMCURV_Module.f90, Line = 110, Column = 80
  IMPLICIT NONE is specified in the local scope, therefore an explicit type must be specified for data object "GAMMA".


ftn-232 crayftn: ERROR ZELEM_EMCURV, File = ../../../gpfs/alpine/gen010/scratch/wspear/testsuite/validation_tests/butterflypack/EMCURV_Module.f90, Line = 116, Column = 59
  IMPLICIT NONE is specified in the local scope, therefore an explicit type must be specified for function "HANKEL02_FUNC".


ftn-292 crayftn: ERROR ZELEM_EMCURV_REAL, File = ../../../gpfs/alpine/gen010/scratch/wspear/testsuite/validation_tests/butterflypack/EMCURV_Module.f90, Line = 134, Column = 7
  "BPACK_DEFS" is specified as the module name on a USE statement, but the compiler cannot find it.


ftn-292 crayftn: ERROR ZELEM_EMCURV_SHIFTED, File = ../../../gpfs/alpine/gen010/scratch/wspear/testsuite/validation_tests/butterflypack/EMCURV_Module.f90, Line = 148, Column = 7
  "BPACK_DEFS" is specified as the module name on a USE statement, but the compiler cannot find it.


ftn-292 crayftn: ERROR VV_POLAR_CURV, File = ../../../gpfs/alpine/gen010/scratch/wspear/testsuite/validation_tests/butterflypack/EMCURV_Module.f90, Line = 182, Column = 7
  "BPACK_DEFS" is specified as the module name on a USE statement, but the compiler cannot find it.


ftn-126 crayftn: ERROR VV_POLAR_CURV, File = ../../../gpfs/alpine/gen010/scratch/wspear/testsuite/validation_tests/butterflypack/EMCURV_Module.f90, Line = 189, Column = 8
  Derived type "MESH" is used to type an object, but is not defined.


ftn-113 crayftn: ERROR VV_POLAR_CURV, File = ../../../gpfs/alpine/gen010/scratch/wspear/testsuite/validation_tests/butterflypack/EMCURV_Module.f90, Line = 192, Column = 9
  IMPLICIT NONE is specified in the local scope, therefore an explicit type must be specified for data object "JUNIT".


ftn-113 crayftn: ERROR VV_POLAR_CURV, File = ../../../gpfs/alpine/gen010/scratch/wspear/testsuite/validation_tests/butterflypack/EMCURV_Module.f90, Line = 192, Column = 75
  IMPLICIT NONE is specified in the local scope, therefore an explicit type must be specified for data object "PI".


ftn-292 crayftn: ERROR RCS_BISTATIC_CURV, File = ../../../gpfs/alpine/gen010/scratch/wspear/testsuite/validation_tests/butterflypack/EMCURV_Module.f90, Line = 201, Column = 7
  "BPACK_DEFS" is specified as the module name on a USE statement, but the compiler cannot find it.


ftn-126 crayftn: ERROR RCS_BISTATIC_CURV, File = ../../../gpfs/alpine/gen010/scratch/wspear/testsuite/validation_tests/butterflypack/EMCURV_Module.f90, Line = 211, Column = 8
  Derived type "MESH" is used to type an object, but is not defined.


ftn-126 crayftn: ERROR RCS_BISTATIC_CURV, File = ../../../gpfs/alpine/gen010/scratch/wspear/testsuite/validation_tests/butterflypack/EMCURV_Module.f90, Line = 214, Column = 8
  Derived type "PROCTREE" is used to type an object, but is not defined.


ftn-113 crayftn: ERROR RCS_BISTATIC_CURV, File = ../../../gpfs/alpine/gen010/scratch/wspear/testsuite/validation_tests/butterflypack/EMCURV_Module.f90, Line = 216, Column = 18
  IMPLICIT NONE is specified in the local scope, therefore an explicit type must be specified for data object "MAIN_ID".


ftn-113 crayftn: ERROR RCS_BISTATIC_CURV, File = ../../../gpfs/alpine/gen010/scratch/wspear/testsuite/validation_tests/butterflypack/EMCURV_Module.f90, Line = 231, Column = 41
  IMPLICIT NONE is specified in the local scope, therefore an explicit type must be specified for data object "MPI_DOUBLE_COMPLEX".


ftn-113 crayftn: ERROR RCS_BISTATIC_CURV, File = ../../../gpfs/alpine/gen010/scratch/wspear/testsuite/validation_tests/butterflypack/EMCURV_Module.f90, Line = 231, Column = 60
  IMPLICIT NONE is specified in the local scope, therefore an explicit type must be specified for data object "MPI_SUM".


ftn-113 crayftn: ERROR RCS_BISTATIC_CURV, File = ../../../gpfs/alpine/gen010/scratch/wspear/testsuite/validation_tests/butterflypack/EMCURV_Module.f90, Line = 233, Column = 13
  IMPLICIT NONE is specified in the local scope, therefore an explicit type must be specified for data object "IMPEDENCE0".


ftn-292 crayftn: ERROR RCS_MONOSTATIC_VV_CURV, File = ../../../gpfs/alpine/gen010/scratch/wspear/testsuite/validation_tests/butterflypack/EMCURV_Module.f90, Line = 248, Column = 7
  "BPACK_DEFS" is specified as the module name on a USE statement, but the compiler cannot find it.


ftn-126 crayftn: ERROR RCS_MONOSTATIC_VV_CURV, File = ../../../gpfs/alpine/gen010/scratch/wspear/testsuite/validation_tests/butterflypack/EMCURV_Module.f90, Line = 257, Column = 8
  Derived type "MESH" is used to type an object, but is not defined.


ftn-126 crayftn: ERROR RCS_MONOSTATIC_VV_CURV, File = ../../../gpfs/alpine/gen010/scratch/wspear/testsuite/validation_tests/butterflypack/EMCURV_Module.f90, Line = 259, Column = 8
  Derived type "PROCTREE" is used to type an object, but is not defined.


ftn-113 crayftn: ERROR RCS_MONOSTATIC_VV_CURV, File = ../../../gpfs/alpine/gen010/scratch/wspear/testsuite/validation_tests/butterflypack/EMCURV_Module.f90, Line = 270, Column = 41
  IMPLICIT NONE is specified in the local scope, therefore an explicit type must be specified for data object "MPI_DOUBLE_COMPLEX".


ftn-113 crayftn: ERROR RCS_MONOSTATIC_VV_CURV, File = ../../../gpfs/alpine/gen010/scratch/wspear/testsuite/validation_tests/butterflypack/EMCURV_Module.f90, Line = 270, Column = 60
  IMPLICIT NONE is specified in the local scope, therefore an explicit type must be specified for data object "MPI_SUM".


ftn-113 crayftn: ERROR RCS_MONOSTATIC_VV_CURV, File = ../../../gpfs/alpine/gen010/scratch/wspear/testsuite/validation_tests/butterflypack/EMCURV_Module.f90, Line = 272, Column = 13
  IMPLICIT NONE is specified in the local scope, therefore an explicit type must be specified for data object "IMPEDENCE0".


ftn-292 crayftn: ERROR ELEMENT_VINC_VV_CURV, File = ../../../gpfs/alpine/gen010/scratch/wspear/testsuite/validation_tests/butterflypack/EMCURV_Module.f90, Line = 282, Column = 7
  "BPACK_DEFS" is specified as the module name on a USE statement, but the compiler cannot find it.


ftn-126 crayftn: ERROR ELEMENT_VINC_VV_CURV, File = ../../../gpfs/alpine/gen010/scratch/wspear/testsuite/validation_tests/butterflypack/EMCURV_Module.f90, Line = 290, Column = 8
  Derived type "MESH" is used to type an object, but is not defined.


ftn-113 crayftn: ERROR ELEMENT_VINC_VV_CURV, File = ../../../gpfs/alpine/gen010/scratch/wspear/testsuite/validation_tests/butterflypack/EMCURV_Module.f90, Line = 293, Column = 9
  IMPLICIT NONE is specified in the local scope, therefore an explicit type must be specified for data object "JUNIT".


ftn-113 crayftn: ERROR ELEMENT_VINC_VV_CURV, File = ../../../gpfs/alpine/gen010/scratch/wspear/testsuite/validation_tests/butterflypack/EMCURV_Module.f90, Line = 293, Column = 74
  IMPLICIT NONE is specified in the local scope, therefore an explicit type must be specified for data object "PI".


ftn-292 crayftn: ERROR GEO_MODELING_CURV, File = ../../../gpfs/alpine/gen010/scratch/wspear/testsuite/validation_tests/butterflypack/EMCURV_Module.f90, Line = 304, Column = 9
  "BPACK_DEFS" is specified as the module name on a USE statement, but the compiler cannot find it.


ftn-113 crayftn: ERROR GEO_MODELING_CURV, File = ../../../gpfs/alpine/gen010/scratch/wspear/testsuite/validation_tests/butterflypack/EMCURV_Module.f90, Line = 427, Column = 32
  IMPLICIT NONE is specified in the local scope, therefore an explicit type must be specified for data object "PI".


ftn-113 crayftn: ERROR GEO_MODELING_CURV, File = ../../../gpfs/alpine/gen010/scratch/wspear/testsuite/validation_tests/butterflypack/EMCURV_Module.f90, Line = 871, Column = 24
  IMPLICIT NONE is specified in the local scope, therefore an explicit type must be specified for data object "BIGVALUE".


ftn-113 crayftn: ERROR GEO_MODELING_CURV, File = ../../../gpfs/alpine/gen010/scratch/wspear/testsuite/validation_tests/butterflypack/EMCURV_Module.f90, Line = 881, Column = 14
  IMPLICIT NONE is specified in the local scope, therefore an explicit type must be specified for data object "MAIN_ID".


ftn-292 crayftn: ERROR EM_SOLVE_CURV, File = ../../../gpfs/alpine/gen010/scratch/wspear/testsuite/validation_tests/butterflypack/EMCURV_Module.f90, Line = 895, Column = 9
  "BPACK_DEFS" is specified as the module name on a USE statement, but the compiler cannot find it.


ftn-292 crayftn: ERROR EM_SOLVE_CURV, File = ../../../gpfs/alpine/gen010/scratch/wspear/testsuite/validation_tests/butterflypack/EMCURV_Module.f90, Line = 896, Column = 6
  "BPACK_SOLVE_MUL" is specified as the module name on a USE statement, but the compiler cannot find it.


ftn-126 crayftn: ERROR EM_SOLVE_CURV, File = ../../../gpfs/alpine/gen010/scratch/wspear/testsuite/validation_tests/butterflypack/EMCURV_Module.f90, Line = 909, Column = 7
  Derived type "HOPTION" is used to type an object, but is not defined.


ftn-126 crayftn: ERROR EM_SOLVE_CURV, File = ../../../gpfs/alpine/gen010/scratch/wspear/testsuite/validation_tests/butterflypack/EMCURV_Module.f90, Line = 910, Column = 7
  Derived type "MESH" is used to type an object, but is not defined.


ftn-126 crayftn: ERROR EM_SOLVE_CURV, File = ../../../gpfs/alpine/gen010/scratch/wspear/testsuite/validation_tests/butterflypack/EMCURV_Module.f90, Line = 912, Column = 7
  Derived type "PROCTREE" is used to type an object, but is not defined.


ftn-126 crayftn: ERROR EM_SOLVE_CURV, File = ../../../gpfs/alpine/gen010/scratch/wspear/testsuite/validation_tests/butterflypack/EMCURV_Module.f90, Line = 913, Column = 7
  Derived type "BMATRIX" is used to type an object, but is not defined.


ftn-126 crayftn: ERROR EM_SOLVE_CURV, File = ../../../gpfs/alpine/gen010/scratch/wspear/testsuite/validation_tests/butterflypack/EMCURV_Module.f90, Line = 914, Column = 7
  Derived type "HSTAT" is used to type an object, but is not defined.


ftn-113 crayftn: ERROR EM_SOLVE_CURV, File = ../../../gpfs/alpine/gen010/scratch/wspear/testsuite/validation_tests/butterflypack/EMCURV_Module.f90, Line = 917, Column = 17
  IMPLICIT NONE is specified in the local scope, therefore an explicit type must be specified for data object "MAIN_ID".


ftn-232 crayftn: ERROR EM_SOLVE_CURV, File = ../../../gpfs/alpine/gen010/scratch/wspear/testsuite/validation_tests/butterflypack/EMCURV_Module.f90, Line = 936, Column = 14
  IMPLICIT NONE is specified in the local scope, therefore an explicit type must be specified for function "OMP_GET_WTIME".


ftn-113 crayftn: ERROR EM_SOLVE_CURV, File = ../../../gpfs/alpine/gen010/scratch/wspear/testsuite/validation_tests/butterflypack/EMCURV_Module.f90, Line = 942, Column = 45
  IMPLICIT NONE is specified in the local scope, therefore an explicit type must be specified for data object "MPI_DOUBLE_PRECISION".


ftn-113 crayftn: ERROR EM_SOLVE_CURV, File = ../../../gpfs/alpine/gen010/scratch/wspear/testsuite/validation_tests/butterflypack/EMCURV_Module.f90, Line = 942, Column = 66
  IMPLICIT NONE is specified in the local scope, therefore an explicit type must be specified for data object "MPI_MAX".


ftn-113 crayftn: ERROR EM_SOLVE_CURV, File = ../../../gpfs/alpine/gen010/scratch/wspear/testsuite/validation_tests/butterflypack/EMCURV_Module.f90, Line = 948, Column = 66
  IMPLICIT NONE is specified in the local scope, therefore an explicit type must be specified for data object "MPI_SUM".


ftn-232 crayftn: ERROR EM_SOLVE_CURV, File = ../../../gpfs/alpine/gen010/scratch/wspear/testsuite/validation_tests/butterflypack/EMCURV_Module.f90, Line = 951, Column = 6
  IMPLICIT NONE is specified in the local scope, therefore an explicit type must be specified for function "SECNDS".


ftn-126 crayftn: ERROR C_EMCURV_INIT, File = ../../../gpfs/alpine/gen010/scratch/wspear/testsuite/validation_tests/butterflypack/EMCURV_Module.f90, Line = 1052, Column = 7
  Derived type "C_PTR" is used to type an object, but is not defined.


ftn-113 crayftn: ERROR C_EMCURV_INIT, File = ../../../gpfs/alpine/gen010/scratch/wspear/testsuite/validation_tests/butterflypack/EMCURV_Module.f90, Line = 1081, Column = 40
  IMPLICIT NONE is specified in the local scope, therefore an explicit type must be specified for data object "MU0".


ftn-113 crayftn: ERROR C_EMCURV_INIT, File = ../../../gpfs/alpine/gen010/scratch/wspear/testsuite/validation_tests/butterflypack/EMCURV_Module.f90, Line = 1081, Column = 44
  IMPLICIT NONE is specified in the local scope, therefore an explicit type must be specified for data object "EPS0".


ftn-113 crayftn: ERROR C_EMCURV_INIT, File = ../../../gpfs/alpine/gen010/scratch/wspear/testsuite/validation_tests/butterflypack/EMCURV_Module.f90, Line = 1082, Column = 21
  IMPLICIT NONE is specified in the local scope, therefore an explicit type must be specified for data object "PI".


ftn-113 crayftn: ERROR C_EMCURV_INIT, File = ../../../gpfs/alpine/gen010/scratch/wspear/testsuite/validation_tests/butterflypack/EMCURV_Module.f90, Line = 1089, Column = 13
  IMPLICIT NONE is specified in the local scope, therefore an explicit type must be specified for data object "MAIN_ID".


ftn-232 crayftn: ERROR C_EMCURV_INIT, File = ../../../gpfs/alpine/gen010/scratch/wspear/testsuite/validation_tests/butterflypack/EMCURV_Module.f90, Line = 1097, Column = 7
  IMPLICIT NONE is specified in the local scope, therefore an explicit type must be specified for function "OMP_GET_WTIME".


ftn-126 crayftn: ERROR C_EMCURV_SAMPLE, File = ../../../gpfs/alpine/gen010/scratch/wspear/testsuite/validation_tests/butterflypack/EMCURV_Module.f90, Line = 1127, Column = 7
  Derived type "C_PTR" is used to type an object, but is not defined.


ftn-289 crayftn: ERROR EMCURV_MODULE, File = ../../../gpfs/alpine/gen010/scratch/wspear/testsuite/validation_tests/butterflypack/EMCURV_Module.f90, Line = 1139, Column = 1
  This END MODULE statement has no matching MODULE statement.

Cray Fortran : Version 12.0.3 (20210816174116_32d4751edd230fbbdc823f8b431bd5155e145fb9)
Cray Fortran : Compile time:  0.0569 seconds
Cray Fortran : 1139 source lines
Cray Fortran : 60 errors, 0 warnings, 0 other messages, 0 ansi
Cray Fortran : "explain ftn-message number" gives more information about each message.
make[2]: *** [CMakeFiles/ie2d.dir/build.make:88: CMakeFiles/ie2d.dir/EMCURV_Module.f90.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:83: CMakeFiles/ie2d.dir/all] Error 2
make: *** [Makefile:91: all] Error 2
```

**Comment by liuyangzhuan** [comment]
@wspear Sorry for the delay. I've fixed these compiling errors for cray fortran. Note that I need Cray > 12 for butterflypack now. It has been updated in the master branch of ButterflyPACK. Could you try it again?

**Comment by wspear** [comment]
I will try to test this out but I believe we need a named/versioned release to add to an E4S release. Do you know when/if a version with this change might be officially released?

**Comment by liuyangzhuan** [comment]
Hi, @wspear I have created a new release v2.1.0, https://github.com/liuyangzhuan/ButterflyPACK/releases/tag/v2.1.0 , which should resolve this issue. It should be ready for an E4S release

**Pull request merged**
