### PR TITLE
Add PaRSEC validation test

### PR DESCRIPTION
**Pull request by abouteiller**
Signed-off-by: Aurelien Bouteiller <bouteill@icl.utk.edu>

### CODE REVIEW

**Comment by abouteiller** [comment]
@sameershende please assign someone to review

**Comment by abouteiller** [comment]
@sameershende we discussed this today in the ecp ST call

**Comment by wspear** [comment]
I tested this with an install of parsec@master on my local linux workstation and got the following error. It looks like maybe CMake isn't finding the location of parsec. The spackLoadUnique operation should set a PARSEC_ROOT environment variable in the run and build environment which can be used to make the location available to the test build if that is helpful.

```
/eaggmsp
/wwooo5i
-- The C compiler identification is GNU 9.3.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Found HWLOC: /home/wspear/bin/SPACK/spack/opt/spack/linux-ubuntu20.04-westmere/gcc-9.3.0/hwloc-2.5.0-i7qzvvdqpzcbkbqs3xuuenlcxorpqwui/lib/libhwloc.so  
-- Performing Test PARSEC_HAVE_HWLOC_PARENT_MEMBER
-- Performing Test PARSEC_HAVE_HWLOC_PARENT_MEMBER - Success
-- Performing Test PARSEC_HAVE_HWLOC_CACHE_ATTR
-- Performing Test PARSEC_HAVE_HWLOC_CACHE_ATTR - Success
-- Performing Test PARSEC_HAVE_HWLOC_OBJ_PU
-- Performing Test PARSEC_HAVE_HWLOC_OBJ_PU - Success
-- Looking for hwloc_bitmap_free in /home/wspear/bin/SPACK/spack/opt/spack/linux-ubuntu20.04-westmere/gcc-9.3.0/hwloc-2.5.0-i7qzvvdqpzcbkbqs3xuuenlcxorpqwui/lib/libhwloc.so
-- Looking for hwloc_bitmap_free in /home/wspear/bin/SPACK/spack/opt/spack/linux-ubuntu20.04-westmere/gcc-9.3.0/hwloc-2.5.0-i7qzvvdqpzcbkbqs3xuuenlcxorpqwui/lib/libhwloc.so - found
-- Found MPI_C: /home/wspear/bin/SPACK/spack/opt/spack/linux-ubuntu20.04-westmere/gcc-9.3.0/openmpi-4.1.1-ll2ut2muu26emtqcbjo5yhwvrohdy53r/lib/libmpi.so (found version "3.1") 
-- Found MPI: TRUE (found version "3.1") found components: C 
-- Found CUDAToolkit: /home/wspear/bin/SPACK/spack/opt/spack/linux-ubuntu20.04-westmere/gcc-9.3.0/cuda-11.3.1-6lhe4vqea4qdudd5vwnakucovaxk6vpq/include (found version "11.3.109") 
-- Configuring done
-- Generating done
-- Build files have been written to: /home/wspear/Code/testsuite/validation_tests/parsec
[ 16%] Generating write_check.h, write_check.c
[ 16%] Built target ptgpp_write_check.write_check
[ 33%] Building C object CMakeFiles/write_check.dir/write_check.c.o
[ 50%] Linking C executable write_check
[ 66%] Built target write_check
[ 83%] Building C object CMakeFiles/dtd_test_allreduce.dir/dtd_test_allreduce.c.o
/home/wspear/Code/testsuite/validation_tests/parsec/dtd_test_allreduce.c:16:10: fatal error: parsec/interfaces/superscalar/insert_function.h: No such file or directory
   16 | #include "parsec/interfaces/superscalar/insert_function.h"
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [CMakeFiles/dtd_test_allreduce.dir/build.make:76: CMakeFiles/dtd_test_allreduce.dir/dtd_test_allreduce.c.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:138: CMakeFiles/dtd_test_allreduce.dir/all] Error 2
make: *** [Makefile:91: all] Error 2
```

**Comment by abouteiller** [comment]
Thanks for testing. I have updated the PR with some version checks to make the tests more resilient to API changes.

**Comment by wspear** [comment]
This worked in my test environment. Thanks.

**Pull request merged**
