### PR TITLE
vtk-m: add smoke test

### PR DESCRIPTION
**Pull request by vicentebolea**
Adds a simple vtk-m smoke test. The smoke test code is taking from the VTK-m canonical smoke test.

### CODE REVIEW

**Comment by vicentebolea** [comment]
ping @egreen77

**Comment by egreen77** [comment]
Not sure I can help with this, maybe you meant @wspear?

**Review by wspear — COMMENTED** [review]
The run log looks like this:

**Comment by vicentebolea** [comment]
@wspear I can definitely print out some info from the binary, however, I was wondering about following the UNIX idiom of no output is successful exit code.

**Comment by wspear** [comment]
As far as the success/failure report issued by the testsuite all that matters is the exit code. Additional log output is just for the benefit of curious/paranoid humans.

**Pull request merged**
