### PR TITLE
Update tasmanian heffte

### PR DESCRIPTION
**Pull request by mkstoyanov**
* moved the Tasmanian and heFFTe testing to the testing script in <install prefix>/share/<project>/testing
* the run command now use ctest which is set by the CMake script
* removed old Tasmanian tests, those files should stay in the Tasmanian repo where they can be properly maintained

### CODE REVIEW

**Review by wspear — CHANGES_REQUESTED** [review]
Greetings. Both of these tests fail on my ubuntu workstation, but they report success because the -e flag is not passed to the bash header. The header should either be `#!/bin/bash -e` or later in the script `set -e` should be called

With heffte I get this error in the compile phase: `CMake Error: The source directory "/home/wspear/bin/SPACK/spack/opt/spack/linux-ubuntu20.04-westmere/gcc-9.3.0/heffte-2.0.0-ayp5aavhganvcvi2m44jil5l2u46vnag/share/heffte/testing" does not exist.`

I'm not sure how to address that. If there is a specific version or variant of heffte that supplies that directory then it should be specified in the spackLoadUnique call.

The tasmanian compile phase fails like: 
  CMake 3.21 or higher is required.  You are running version 3.18.2

This can be fixed by making the cmake load call in compile.sh like:
`spackLoadUnique cmake@3.21:`

**Comment by mkstoyanov** [comment]
* added the `bash -e` to the first line
* this works with the latest heffte@2.2.0 and latest tasmanian@7.7
    * I don't think the old tests work for the previous versions anyway, e.g., some of the heffte tests require specific number of MPI ranks which is not reflected in the test, while tasmanian did not test all the features as it did not include any of the python examples
* the goal here is to move to testing using a single CMake file that is supported in the main tasmaian/heffte repos and thus make this repo independent from the version in the future; if we have to test older versions, then how far back should we go?
* the CMake issue is due to the wrong version being picked up, e.g., if tasmanian is build with 3.21 then that should be loaded by the testing environment, I think the issue is resolved in the latest spack by making cmake a runtime dependence

**Comment by mkstoyanov** [comment]
I also don't understand why we have this repo when we already have `spack test run <package>`.

**Comment by wspear** [comment]
If your internal spack tests are ready for primetime and provide coverage equivalent to the tests that were formerly in the testsuite you can use them instead. Just skip the compile phase (have it echo a message saying it isn't needed) and invoke the test in the run phase like: `spackTestRun $<PACKAGE>_HASH`

See the hdf5 test for an example of this.

Having setup.sh load the packages with a version constraint so the tests will work or won't run at all (i.e. `spackLoadUnique heffte@2.2.0:` ) is probably the only backward compatibility you need to worry about. I'm using the latest pull of spack and still getting that make version error but if cmake as a runtime dependency is coming soon it will be nice when specifying the minimum cmake version is no longer necessary.

**Comment by mkstoyanov** [comment]
@wspear This makes sense now. Thanks for clarifying!

I had to remove the `spackLoadUnique cmake` directives which makes `spackLoadUnique heffte@2.2.0:` load the correct version.

**Comment by wspear** [comment]
Nice! We're glad to be getting testing moved to the spack side, and especially glad to be getting source code out of the testsuite repo. Just one final request, could you remove the -x from the bash headers? It causes too much background spack activity to print and clogs up the log files.

**Comment by mkstoyanov** [comment]
Removed the `-x`.

This is much more sustainable now.

This repo and spack should not contain testing code beyond a reference to the testing code from the project repo. The testing code is part of the project and must sit in the same repo to be maintained and updated with the rest of the code. Thus, we can keep the code and testing in lock-step without making PRs across multiple repos. I think holds for the other projects too.

**Comment by wspear** [comment]
Yes, we're trying to move in that direction across the board.

**Pull request merged**
