### PR TITLE
In strumpack test, check return codes, solution

### PR DESCRIPTION
**Pull request by pghysels**
Check ReturnCode for various operations.
Check the backward error of the linear solve.

### CODE REVIEW

**Comment by shahzebsiddiqui** [comment]
@wspear when you have chance please review this MR so we can test this out in https://github.com/buildtesters/buildtest-cori/pull/73

**Review by wspear — COMMENTED** [review]
I get a segmentation fault running this test against strumpack@6.0.0 on my local ubuntu workstation. Is a particular install variant needed or other modification to the build/run environment? The error was similar before and after applying this PR.

```
solving 2D 100x100 Poisson problem with 10 right hand sides
# Initializing STRUMPACK
# using 4 OpenMP thread(s)
# number of tasking levels = 5 = log_2(#threads) + 3
# matrix equilibration, r_cond = 1 , c_cond = 1 , type = N
# initial matrix:
#   - number of unknowns = 10,000
#   - number of nonzeros = 49,600
# nested dissection reordering:
#   - Geometric reordering
#   - strategy parameter = 8
#   - number of separators = 1,967
#   - number of levels = 12
#   - nd time = 0.00102487
#   - symmetrization time = 7.2713e-07
# symbolic factorization:
#   - nr of dense Frontal matrices = 1,967
#   - symb-factor time = 0.000899583
# multifrontal factorization:
#   - estimated memory usage (exact solver) = 4.50818 MB
#   - minimum pivot, sqrt(eps)*|A|_1 = 8.42937e-08
#   - replacing of small pivots is not enabled
#   - factor time = 0.00802377
#   - factor nonzeros = 563,522
#   - factor memory = 4.50818 MB
REFINEMENT it. 0        res =      1418.17      rel.res =            1  bw.error =            1
REFINEMENT it. 1        res =   2.0179e-13      rel.res =  1.42289e-16  bw.error =   5.6619e-16
# DIRECT/GMRES solve:
#   - abs_tol = 1e-10, rel_tol = 1e-06, restart = 30, maxit = 5000
#   - number of Krylov iterations = 1
#   - solve time = 0.0068464
# COMPONENTWISE SCALED RESIDUAL = 5.34735e-16
# relative error = ||x-x_exact||_F/||x_exact||_F = 3.99487e-15
solving 2D 100x100 Poisson problem with 10 right hand sides
# Initializing STRUMPACK
# using 4 OpenMP thread(s)
# number of tasking levels = 5 = log_2(#threads) + 3
# using 8 MPI processes
# matrix equilibration, r_cond = 1 , c_cond = 1 , type = N
# initial matrix:
#   - number of unknowns = 10,000
#   - number of nonzeros = 49,600
# nested dissection reordering:
#   - Geometric reordering
#   - strategy parameter = 8
#   - number of separators = 1,967
#   - number of levels = 9
#   - nd time = 0.000819376
#   - symmetrization time = 5.9302e-07
# symbolic factorization:
#   - nr of dense Frontal matrices = 1,967
#   - symb-factor time = 0.0371764
# multifrontal factorization:
#   - estimated memory usage (exact solver) = 4.50818 MB
#   - minimum pivot, sqrt(eps)*|A|_1 = 8.42937e-08
#   - replacing of small pivots is not enabled
[yu:1782669] *** Process received signal ***
[yu:1782669] Signal: Segmentation fault (11)
[yu:1782669] Signal code: Address not mapped (1)
[yu:1782669] Failing at address: 0xffffffffffffffe0
[yu:1782669] [ 0] /lib/x86_64-linux-gnu/libc.so.6(+0x46210)[0x7f588052e210]
[yu:1782669] [ 1] /home/wspear/bin/SPACK/spack/opt/spack/linux-ubuntu20.04-westmere/gcc-9.3.0/slate-2021.05.02-bquvp6pytzbapf7eudvxq6tto2xhbhrx/lib/libslate.so(_ZNSt8_Rb_treeISt5tupleIJllEES1_St9_IdentityIS1_ESt4lessIS1_ESaIS1_EE16_M_insert_uniqueIS1_EESt4pairISt17_Rb_tree_iteratorIS1_EbEOT_+0x1c)[0x7f587e9f8c6c]
[yu:1782669] [ 2] /home/wspear/bin/SPACK/spack/opt/spack/linux-ubuntu20.04-westmere/gcc-9.3.0/slate-2021.05.02-bquvp6pytzbapf7eudvxq6tto2xhbhrx/lib/libslate.so(_ZN5slate10BaseMatrixIdE29tileGetAllForWritingOnDevicesENS_13LayoutConvertE+0x14b)[0x7f587eb17a0b]
[yu:1782669] [ 3] [yu:1782667] *** Process received signal ***
[yu:1782667] Signal: Segmentation fault (11)
[yu:1782667] Signal code: Address not mapped (1)
[yu:1782667] Failing at address: 0xffffffffffffffe0
/home/wspear/bin/SPACK/spack/opt/spack/linux-ubuntu20.04-westmere/gcc-9.3.0/slate-2021.05.02-bquvp6pytzbapf7eudvxq6tto2xhbhrx/lib/libslate.so(+0x226b96)[0x7f587eb17b96]
[yu:1782667] [ 0] /lib/x86_64-linux-gnu/libc.so.6(+0x46210)[0x7f67470d3210]
[yu:1782667] [ 1] /home/wspear/bin/SPACK/spack/opt/spack/linux-ubuntu20.04-westmere/gcc-9.3.0/slate-2021.05.02-bquvp6pytzbapf7eudvxq6tto2xhbhrx/lib/libslate.so(_ZNSt8_Rb_treeISt5tupleIJllEES1_St9_IdentityIS1_ESt4lessIS1_ESaIS1_EE16_M_insert_uniqueIS1_EESt4pairISt17_Rb_tree_iteratorIS1_EbEOT_+0x1c)[0x7f674559dc6c]
[yu:1782669] [ 4] /usr/lib/x86_64-linux-gnu/libgomp.so.1(+0x15754)[0x7f587e792754]
[yu:1782669] [ 5] /usr/lib/x86_64-linux-gnu/libgomp.so.1(+0x1d368)[0x7f587e79a368]
[yu:1782669] [ 6] /usr/lib/x86_64-linux-gnu/libgomp.so.1(+0x1a79a)[0x7f587e79779a]
[yu:1782669] [ 7] [yu:1782667] [ 2] /lib/x86_64-linux-gnu/libpthread.so.0(+0x9609)[0x7f587df5a609]
/home/wspear/bin/SPACK/spack/opt/spack/linux-ubuntu20.04-westmere/gcc-9.3.0/slate-2021.05.02-bquvp6pytzbapf7eudvxq6tto2xhbhrx/lib/libslate.so(_ZN5slate10BaseMatrixIdE29tileGetAllForWritingOnDevicesENS_13LayoutConvertE+0x14b)[0x7f67456bca0b]
[yu:1782667] [ 3] [yu:1782669] /home/wspear/bin/SPACK/spack/opt/spack/linux-ubuntu20.04-westmere/gcc-9.3.0/slate-2021.05.02-bquvp6pytzbapf7eudvxq6tto2xhbhrx/lib/libslate.so(+0x226b96)[0x7f67456bcb96]
[yu:1782667] [ 4] /usr/lib/x86_64-linux-gnu/libgomp.so.1(+0x15754)[0x7f6745337754]
[yu:1782667] [ 5] /usr/lib/x86_64-linux-gnu/libgomp.so.1(+0x1d368)[0x7f674533f368]
[yu:1782667] [ 6] /usr/lib/x86_64-linux-gnu/libgomp.so.1(+0x1a79a)[0x7f674533c79a]
[yu:1782667] [ 7] /lib/x86_64-linux-gnu/libpthread.so.0(+0x9609)[0x7f6744aff609]
[yu:1782667] [ 8] [ 8] /lib/x86_64-linux-gnu/libc.so.6(clone+0x43)[0x7f67471af293]
[yu:1782667] *** End of error message ***
/lib/x86_64-linux-gnu/libc.so.6(clone+0x43)[0x7f588060a293]
[yu:1782669] *** End of error message ***
[yu:1782663] *** Process received signal ***
[yu:1782663] Signal: Segmentation fault (11)
[yu:1782663] Signal code: Address not mapped (1)
[yu:1782663] Failing at address: 0xffffffffffffffe0
[yu:1782663] [ 0] /lib/x86_64-linux-gnu/libc.so.6(+0x46210)[0x7f53b1bdb210]
[yu:1782663] [ 1] /home/wspear/bin/SPACK/spack/opt/spack/linux-ubuntu20.04-westmere/gcc-9.3.0/slate-2021.05.02-bquvp6pytzbapf7eudvxq6tto2xhbhrx/lib/libslate.so(_ZNSt8_Rb_treeISt5tupleIJllEES1_St9_IdentityIS1_ESt4lessIS1_ESaIS1_EE16_M_insert_uniqueIS1_EESt4pairISt17_Rb_tree_iteratorIS1_EbEOT_+0x1c)[0x7f53b00a5c6c]
[yu:1782663] [ 2] /home/wspear/bin/SPACK/spack/opt/spack/linux-ubuntu20.04-westmere/gcc-9.3.0/slate-2021.05.02-bquvp6pytzbapf7eudvxq6tto2xhbhrx/lib/libslate.so(_ZN5slate10BaseMatrixIdE29tileGetAllForWritingOnDevicesENS_13LayoutConvertE+0x14b)[0x7f53b01c4a0b]
[yu:1782663] [ 3] /home/wspear/bin/SPACK/spack/opt/spack/linux-ubuntu20.04-westmere/gcc-9.3.0/slate-2021.05.02-bquvp6pytzbapf7eudvxq6tto2xhbhrx/lib/libslate.so(+0x226b96)[0x7f53b01c4b96]
[yu:1782663] [ 4] /usr/lib/x86_64-linux-gnu/libgomp.so.1(+0x15754)[0x7f53afe3f754]
[yu:1782663] [ 5] /usr/lib/x86_64-linux-gnu/libgomp.so.1(+0x1d368)[0x7f53afe47368]
[yu:1782663] [ 6] /usr/lib/x86_64-linux-gnu/libgomp.so.1(+0x1a79a)[0x7f53afe4479a]
[yu:1782663] [ 7] /lib/x86_64-linux-gnu/libpthread.so.0(+0x9609)[0x7f53af607609]
[yu:1782663] [ 8] /lib/x86_64-linux-gnu/libc.so.6(clone+0x43)[0x7f53b1cb7293]
[yu:1782663] *** End of error message ***
[yu:1782665] *** Process received signal ***
[yu:1782665] Signal: Segmentation fault (11)
[yu:1782665] Signal code: Address not mapped (1)
[yu:1782665] Failing at address: 0xffffffffffffffe0
[yu:1782665] [ 0] /lib/x86_64-linux-gnu/libc.so.6(+0x46210)[0x7fd0879b2210]
[yu:1782665] [ 1] /home/wspear/bin/SPACK/spack/opt/spack/linux-ubuntu20.04-westmere/gcc-9.3.0/slate-2021.05.02-bquvp6pytzbapf7eudvxq6tto2xhbhrx/lib/libslate.so(_ZNSt8_Rb_treeISt5tupleIJllEES1_St9_IdentityIS1_ESt4lessIS1_ESaIS1_EE16_M_insert_uniqueIS1_EESt4pairISt17_Rb_tree_iteratorIS1_EbEOT_+0x1c)[0x7fd085e7cc6c]
[yu:1782665] [ 2] /home/wspear/bin/SPACK/spack/opt/spack/linux-ubuntu20.04-westmere/gcc-9.3.0/slate-2021.05.02-bquvp6pytzbapf7eudvxq6tto2xhbhrx/lib/libslate.so(_ZN5slate10BaseMatrixIdE29tileGetAllForWritingOnDevicesENS_13LayoutConvertE+0x14b)[0x7fd085f9ba0b]
[yu:1782665] [ 3] /home/wspear/bin/SPACK/spack/opt/spack/linux-ubuntu20.04-westmere/gcc-9.3.0/slate-2021.05.02-bquvp6pytzbapf7eudvxq6tto2xhbhrx/lib/libslate.so(+0x226b96)[0x7fd085f9bb96]
[yu:1782665] [ 4] /usr/lib/x86_64-linux-gnu/libgomp.so.1(+0x15754)[0x7fd085c16754]
[yu:1782665] [ 5] /usr/lib/x86_64-linux-gnu/libgomp.so.1(+0x1d368)[0x7fd085c1e368]
[yu:1782665] [ 6] /usr/lib/x86_64-linux-gnu/libgomp.so.1(+0x1a79a)[0x7fd085c1b79a]
[yu:1782665] [ 7] /lib/x86_64-linux-gnu/libpthread.so.0(+0x9609)[0x7fd0853de609]
[yu:1782665] [ 8] /lib/x86_64-linux-gnu/libc.so.6(clone+0x43)[0x7fd087a8e293]
[yu:1782665] *** End of error message ***
--------------------------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code. Per user-direction, the job has been aborted.
--------------------------------------------------------------------------
--------------------------------------------------------------------------
mpirun noticed that process rank 0 with PID 0 on node yu exited on signal 11 (Segmentation fault).
--------------------------------------------------------------------------
```

On spock with strumpack@5.1.1 I get this error both before and after PR:

```
solving 2D 100x100 Poisson problem with 10 right hand sides
# Initializing STRUMPACK
# using 4 OpenMP thread(s)
# number of tasking levels = 5 = log_2(#threads) + 3
# matrix equilibration, r_cond = 1 , c_cond = 1 , type = N
# initial matrix:
#   - number of unknowns = 10,000
#   - number of nonzeros = 49,600
# nested dissection reordering:
#   - Geometric reordering
#   - strategy parameter = 8
#   - number of separators = 2,097
#   - number of levels = 12
#   - nd time = 0.00151292
#   - symmetrization time = 1.1201e-05
# symbolic factorization:
#   - nr of dense Frontal matrices = 2,097
#   - symb-factor time = 0.00238362
# multifrontal factorization:
#   - estimated memory usage (exact solver) = 4.41688 MB
#   - minimum pivot, sqrt(eps)*|A|_1 = 8.42937e-08
#   - replacing of small pivots is not enabled
FATAL ERROR: CCE OpenMP does not yet support GNU entry point "GOMP_taskloop_ull"
FATAL ERROR: CCE OpenMP does not yet support GNU entry point "GOMP_taskloop_ull"
```

**Comment by pghysels** [comment]
The first error comes from the SLATE dependency. I did not see this when I tested on cori with e4s-21.05, perhaps that has STRUMPACK with ~slate?
The other error is from the Cray compiler, and the combination with GNU OpenMP? I never tested with the Cray compiler. 
I will look into both problems.
Thank you.

**Comment by pghysels** [comment]
There was an issue that when the code is compiled with SLATE but without CUDA, it would still try to use the GPU through SLATE, which failed. I made a change in the code, and in the test now explicitly disable GPU.

For the Cray compiler, I tried to debug this but it seems there is a problem with the openmp taskloop implementation in the Cray compiler. So I just set the number of threads to 1 in the test.

Could you try it again?

**Pull request merged**
